### ISSUE TITLE
SQL 데이터 초기화 스크립트 파일 이름이 data-mysql.sql 로 되어있던데 어떻게 실행하지?

### ISSUE THREAD

**Issue by mklinkj** [mklinkj/spring-boot-persistence-best-practices-study#4]
## 문제
저자님 예제를 보면 sql 초기화 스크립트 파일이 그냥 data.sql이 아니고 -mysql이 붙어있다.

그냥 실행하면 실행이 안되었다.

## 해결
```yml
# application.yml
spring:
  sql:
    init:
      mode: always
      platform: mysql # data-{platform}.sql 형식의 파일을 읽어서 초기화한다.
  jpa:
    defer-datasource-initialization: true

```

옵션을 살펴보니 `spring.sql.init.platform` 에 플랫폼 명칭을 지정해줄 수 있었다.
이후 잘 읽음.

저자님 application.properties 설정 다시보니 설정이 있었음... 내가 놓쳤다... 😅
