### ISSUE TITLE
테이블 삭제를 위한 프로시저 추가 및 사용

### ISSUE THREAD

**Issue by mklinkj** [mklinkj/spring-boot-persistence-best-practices-study#6]
## 문제
다른 JPA 스터디 할 때도 경험했지만... 

각 챕터를 진행하다보면 이전 챕터의 외래 키 관계가 남아서,

테이블을 순서대로 수동으로 지워주지 않으면 테이블 삭제가 자동으로 안되어서 문제가 생길 때가 많았다. 😂

그 때 해결한 방식 대로... 해당 스터디 데이터베이스의 모든 테이블을 DROP 해주는 스크립트를 만들어 사용하자!

#### drop_all_tables 프로시저 등록
```sql
DROP PROCEDURE IF EXISTS `drop_all_tables`;

DELIMITER $$
CREATE PROCEDURE `drop_all_tables`()
BEGIN
    DECLARE _done INT DEFAULT FALSE;
    DECLARE _tableName VARCHAR(255);
    DECLARE _cursor CURSOR FOR
        SELECT table_name 
        FROM information_schema.TABLES
        WHERE table_schema = SCHEMA();
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET _done = TRUE;

    SET FOREIGN_KEY_CHECKS = 0;

    OPEN _cursor;

    REPEAT FETCH _cursor INTO _tableName;

    IF NOT _done THEN
        SET @stmt_sql = CONCAT('DROP TABLE ', '`', _tableName, '`');
        PREPARE stmt1 FROM @stmt_sql;
        EXECUTE stmt1;
        DEALLOCATE PREPARE stmt1;
    END IF;

    UNTIL _done END REPEAT;

    CLOSE _cursor;
    SET FOREIGN_KEY_CHECKS = 1;
END$$

DELIMITER ;
```

#### drop 스크립트에서 호출
```sql
CALL drop_all_tables(); 
```

#### application.yml에서의 처리
스프링 부트에서 제공하는 옵션으로 지정하다 보면 순서를 정확하게 맞추기가 힘들다. 표준 Jakarta JPA 프로퍼티를 전달하여 해결하자!
```yml
# application.yml
spring:
  jpa:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
            # DB의 모든 테이블을 삭제하는 MySQL 함수를 만들어둔 상태, DROP은 전체 테이블 삭제 프로시저 호출로만 해결한다.
            drop-source: script
            drop-script-source: sql/mysql/all-drop.sql
            create-source: metadata-then-script
            create-script-source: sql/mysql/data.sql # 데이터가 있을 때, 넣어주자.
```

* data.sql의 경우, 일단 설정을 했다면 해당 파일에 쿼리가 하나라도 들어가야 한다. 초기에 넣어줄 데이터가 없을 경우 해당 파일 내용에 `SELECT 1` 또는 `SELECT VERSION()` 같은 단순 쿼리를 넣어주면 된다.
